# Generated by Django 5.1.3 on 2025-04-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0002_rename_name_kril_bannermodel_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='name_en',
            new_name='name_kril',
        ),
    ]
