# Generated by Django 5.1.3 on 2025-04-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0003_rename_name_en_bannermodel_name_kril'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='chegirma foizi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Chegirma bormi ?'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
