# Generated by Django 5.1.3 on 2025-04-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0005_alter_bookmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book-image/', verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='BookimageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='book-image/', verbose_name='Rasm')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.bookmodel', verbose_name='Kitob')),
            ],
            options={
                'verbose_name': 'BookimageModel',
                'verbose_name_plural': 'BookimageModels',
                'db_table': 'bookImage',
            },
        ),
    ]
