# Generated by Django 5.1.3 on 2025-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0007_bookmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kitob soni'),
        ),
    ]
