# Generated by Django 5.1.3 on 2025-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0008_bookmodel_description_alter_bookmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description_kril',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
    ]
