# Generated by Django 5.1.3 on 2025-04-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0009_bookmodel_description_kril_bookmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='category-image/', verbose_name='Rasm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
