# Generated by Django 5.1.3 on 2025-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0012_auto_20250523_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Payment link'),
        ),
    ]
