# Generated by Django 5.1.3 on 2025-08-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0013_ordermodel_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimagemodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_images', to='havasbook.bookmodel', verbose_name='Kitob'),
        ),
    ]
