# Generated by Django 5.1.3 on 2025-04-08 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0014_alter_locationmodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Buyrtma uchun izoh'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_method',
            field=models.CharField(choices=[('door_delivery', "Eski uyga (Toshkent bo'ylab kur'er orqali yetkazib berish) 20.000~35.000 so'm"), ('pickup_point', "Yetkazib berish nuqtasiga (BTS pochta orqali O'zbekiston bo'ylab) 25.000~50.000 so'm")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='havasbook.locationmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Uzum karta')], default='click', max_length=50, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderitemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='havasbook.bookmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='havasbook.ordermodel')),
            ],
            options={
                'verbose_name': 'OrderitemModel',
                'verbose_name_plural': 'OrderitemModels',
                'db_table': 'orderITem',
            },
        ),
    ]
