# Generated by Django 5.1.3 on 2025-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0018_alter_cartmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='latitude',
            field=models.FloatField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='longitude',
            field=models.FloatField(verbose_name='Uzunlik'),
        ),
    ]
