# Generated by Django 5.1.3 on 2025-04-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0020_alter_orderitemmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='havasbook.bookmodel'),
        ),
    ]
