# Generated by Django 5.1.3 on 2025-04-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0021_alter_orderitemmodel_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'verbose_name': 'Orderitem', 'verbose_name_plural': 'Orderitems'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelTable(
            name='orderitemmodel',
            table='orderitem',
        ),
    ]
