# Generated by Django 5.1.3 on 2025-04-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0022_alter_orderitemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'verbose_name': 'OrderitemModel', 'verbose_name_plural': 'OrderitemModels'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'OrderModel', 'verbose_name_plural': 'OrderModels'},
        ),
        migrations.AlterModelTable(
            name='orderitemmodel',
            table='orderITem',
        ),
    ]
