# Generated by Django 5.1.3 on 2025-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0024_ordermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqam'),
        ),
    ]
