# Generated by Django 5.1.3 on 2025-04-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0026_alter_locationmodel_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='name_kril',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='name_uz',
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='latitude',
            field=models.FloatField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='longitude',
            field=models.FloatField(verbose_name='Uzunlik'),
        ),
    ]
