# Generated by Django 5.1.3 on 2025-04-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0027_remove_bannermodel_name_remove_bannermodel_name_kril_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='views',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='havasbook.categorymodel', verbose_name='Kategoriylar'),
        ),
    ]
