# Generated by Django 5.1.3 on 2025-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0028_remove_bookmodel_views_bookmodel_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Oldindan buyurtma bormi?'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sotilganlar soni'),
        ),
    ]
