# Generated by Django 5.1.3 on 2025-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0030_productsmodel_productsimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='description_kril',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
