# Generated by Django 5.1.3 on 2025-04-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0031_productsmodel_description_kril_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foydalanuvchi ismi')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqam')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='havasbook.bookmodel')),
            ],
            options={
                'verbose_name': 'PreorderModel',
                'verbose_name_plural': 'PreorderModels',
                'db_table': 'preorder',
            },
        ),
    ]
