# Generated by Django 5.1.3 on 2025-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0033_alter_preordermodel_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='book-color/', verbose_name='Rangi')),
            ],
            options={
                'verbose_name': 'ColorModel',
                'verbose_name_plural': 'ColorModels',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'SizeModel',
                'verbose_name_plural': 'SizeModels',
                'db_table': 'size',
            },
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='color',
            field=models.ManyToManyField(blank=True, to='havasbook.colormodel', verbose_name='Mahsulot Rangi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='size',
            field=models.ManyToManyField(blank=True, to='havasbook.sizemodel', verbose_name="O'lchami"),
        ),
    ]
