# Generated by Django 5.1.3 on 2025-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0034_colormodel_sizemodel_bookmodel_color_bookmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Rang Nomi'),
            preserve_default=False,
        ),
    ]
