# Generated by Django 5.1.3 on 2025-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0035_colormodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='title',
            field=models.CharField(default=1, verbose_name='Rang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='title',
            field=models.CharField(default=1, verbose_name="O'lcham"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name="O'lcham nomi"),
        ),
    ]
