# Generated by Django 5.1.3 on 2025-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0036_colormodel_title_sizemodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='name_kril',
            field=models.CharField(max_length=50, null=True, verbose_name='Rang Nomi'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Rang Nomi'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Rang Nomi'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_kril',
            field=models.CharField(null=True, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_uz',
            field=models.CharField(null=True, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name="O'lcham nomi"),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="O'lcham nomi"),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="O'lcham nomi"),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='title_kril',
            field=models.CharField(null=True, verbose_name="O'lcham"),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='title_ru',
            field=models.CharField(null=True, verbose_name="O'lcham"),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='title_uz',
            field=models.CharField(null=True, verbose_name="O'lcham"),
        ),
    ]
