# Generated by Django 5.1.3 on 2025-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0037_colormodel_name_kril_colormodel_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Mahlulot Soni'),
        ),
    ]
