# Generated by Django 5.1.3 on 2025-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0041_remove_cartitemmodel_color_remove_cartitemmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Mashhurmi ?'),
        ),
    ]
