# Generated by Django 5.1.3 on 2025-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0043_cartitemmodel_color_cartitemmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('delivered', 'Topshirilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=50, verbose_name='Status'),
        ),
    ]
