# Generated by Django 5.1.3 on 2025-04-18 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0044_alter_ordermodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preorder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
