# Generated by Django 5.1.3 on 2025-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0045_preordermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul qilindi', 'Qabul qilindi'), ('bekor qilindi', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Status'),
        ),
    ]
