# Generated by Django 5.1.3 on 2025-04-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0047_alter_preordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havasbook.colormodel'),
        ),
        migrations.AddField(
            model_name='preordermodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='havasbook.sizemodel'),
        ),
    ]
