# Generated by Django 5.1.3 on 2025-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0048_preordermodel_color_preordermodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
