# Generated by Django 5.1.3 on 2025-04-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0049_preordermodel_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'DeliveryModel',
                'verbose_name_plural': 'DeliveryModels',
                'db_table': 'delivery',
            },
        ),
    ]
