# Generated by Django 5.1.3 on 2025-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0050_deliverymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='title_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
