# Generated by Django 5.1.3 on 2025-04-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0051_deliverymodel_title_kril_deliverymodel_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivery_method',
        ),
    ]
