# Generated by Django 5.1.3 on 2025-04-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0052_remove_ordermodel_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='havasbook.deliverymodel'),
        ),
    ]
