# Generated by Django 5.1.3 on 2025-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0053_ordermodel_delivery_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='name',
            new_name='title',
        ),
    ]
