# Generated by Django 5.1.3 on 2025-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0054_rename_name_locationmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='locationmodel',
            old_name='longitude',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='phone',
            new_name='reciever_phone',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ism'),
        ),
    ]
