# Generated by Django 5.1.3 on 2025-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0056_alter_locationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='reciever_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqam'),
        ),
    ]
