# Generated by Django 5.1.3 on 2025-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0057_alter_ordermodel_reciever_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqt pul'), ('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Uzum karta')], default='click', max_length=50, verbose_name="To'lov turi"),
        ),
    ]
