# Generated by Django 5.1.3 on 2025-04-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0058_deliverymodel_price_alter_ordermodel_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Narxi'),
        ),
    ]
