# Generated by Django 5.1.3 on 2025-04-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0059_alter_deliverymodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
