# Generated by Django 5.1.3 on 2025-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0060_rename_total_amount_ordermodel_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='title_kril',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
